config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#home'

  resources :projects do
    resources :buggs do
      member do
        get :start_working
        get :in_progress
        get :completed
      end
    end
  end

  get 'dashboard/developer', to: 'dashboard#developer'
  get 'dashboard/manager', to: 'dashboard#manager'
  get 'dashboard/qa', to: 'dashboard#qa'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bugg.rb
# frozen_string_literal: true

class Bugg < ApplicationRecord
  validates :state, presence: true

  has_one_attached :image

  belongs_to :project
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :buggs, dependent: :destroy
  has_many :project_users
  has_many :users, through: :project_users, dependent: :destroy

  validates :title, :description, presence: true, length: { minimum: 5 }
end

app/models/project_user.rb
# frozen_string_literal: true

class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { manager: 0, developer: 1, qa: 2 }

  has_many :project_users, dependent: :destroy
  has_many :projects, through: :project_users
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[role name])
  end
end

app/controllers/buggs_controller.rb
# frozen_string_literal: true

class BuggsController < ApplicationController
  before_action :find_bugg, only: %i[show edit update destroy]

  def index
    @buggs = Bugg.all
  end

  def new
    @project = Project.find(params[:project_id])
    @bugg = @project.buggs.build

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @project = Project.find(params[:project_id])

    respond_to do |format|
      if @project.buggs.create(bugg_params)
        @buggs = Bugg.all

        format.html { redirect_to project_path(@project), notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bugg }
        format.js
      else
        f.html { render :new, status: :unprocessable_entity }
        f.json { render json: @bugg.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @bugg = @project.buggs.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @bugg = @project.buggs.find(params[:id])

    respond_to do |f|
      if @bugg.update(bugg_params)
        f.html { redirect_to project_path(@project), notice: 'Bug was successfully updated.' }
        f.json { render :show, status: :ok, location: @bugg }
      else
        f.html { render :edit, status: :unprocessable_entity }
        f.json { render json: @bugg.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def destroy
    @bugg.destroy
    redirect_to project_url
  end

  def start_working
    @project = Project.find(params[:project_id])
    @bugg = @project.buggs.find(params[:id])

    if @bugg.update(state: 'started')
      redirect_to project_path(@project), notice: 'Started Successfully'
    else
      redirect_to project_path(@project)
    end
  end

  def in_progress
    @project = Project.find(params[:project_id])
    @bugg = @project.buggs.find(params[:id])
    if @bugg.update(state: 'inprogress')
      redirect_to project_path(@project), notice: 'Started Successfully'
    else
      redirect_to project_path(@project)
    end
  end

  def completed
    @project = Project.find(params[:project_id])
    @bugg = @project.buggs.find(params[:id])
    if @bugg.update(state: 'completed')
      redirect_to project_path(@project), notice: 'Completed Successfully'
    else
      redirect_to project_path(@project)
    end
  end

  private

  def find_bugg
    @bugg = Bugg.find_by_id(params[:id])
  end

  def bugg_params
    params.require(:bugg).permit(:title, :image, :description, :startdate, :status, :state)
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def home
    @projects = if current_user.developer?
                  current_user.projects
                else
                  Project.all
                end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :find_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
         @projects = Project.all
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  private

  def find_project
    @project = Project.find_by_id(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, user_ids: [])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/buggs/_bugg.html.erb
<div class = "w-25 container text-center text-black">
  <%= form_for ([@project, @bugg]), html: {multipart: true}, remote: true do |f| %>
  <strong>Create Project Bug</strong>
    <div>
      <%= f.label :Title %><br>
      <%= f.text_field :title, class: 'form-control'%><br>
    </div>
    <br>
    <div>
      <%= f.label :Description %><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <br>
    <div>
      <%= f.label :startdate %><br>
      <%= f.datetime_field :startdate, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :image %><br>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
    <br>
    <%=f.submit"Submit", class: 'btn btn-success ml-3' %>
    </div>
  <% end %>
</div>

app/views/buggs/_bugg_table.html.erb
<div class= "container p-1 mb-2 bg-hide text-white text-center">
  <table class="table  text-white ">
    <thead class="thead-dark">
      <tr>
        <th scope= "col">Bug Title</th>
        <th scope= "col">Description</th>
        <th scope= "col">Start date</th>
        <th scope= "col">Bug Screenshot</th>
        <% if current_user.role == "qa" %>
          <th scope= "col">Actions</th>
        <% end %>
        <% if current_user.role == "developer" %>
          <th scope= "col">State</th>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @project.buggs.each do |bugg|%>
        <tr>
          <td><%= bugg.title%></td>
          <td><%= bugg.description%></td>
          <td><%= bugg.startdate%></td>
          <% if bugg.image.attached? %>
            <td><%= image_tag bugg.image, size: "75x75" %></td>
          <% else %>
            <td> <%= image_tag "download.jpeg", size: "75x75" %></td>
          <% end %>
          <% if current_user.developer? %>
            <td>
              <%= link_to bugg.state, start_working_project_bugg_path(bugg.project, bugg.id), class: "btn btn-outline-primary" if bugg.state == 'new created' %>
              <%= link_to bugg.state, in_progress_project_bugg_path(bugg.project, bugg.id), :class=>"btn btn-outline-primary" if bugg.state == 'started' %>
              <%= link_to bugg.state, completed_project_bugg_path(bugg.project, bugg.id), :class=>"btn btn-outline-primary" if bugg.state == 'inprogress' %>
              <%= link_to bugg.state, completed_project_bugg_path(bugg.project, bugg.id), :class=>"btn btn-outline-primary" if bugg.state == 'completed' %>
            </td>
          <% end %>
          <td>
            <% if current_user.role == "qa" %>
              <%= link_to "", edit_project_bugg_url(bugg.project, bugg.id), class: "fa-solid fa-pen-to-square" %>
              <%= link_to "", project_bugg_path(bugg.project,bugg.id), method: :delete, class: "fa-solid fa-trash" %>
          </td>
            <%end%>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/buggs/_showbug.html.erb
<div class= "container p-1 mb-2 bg-hide text-white text-center">
  <table class="table  text-white ">
    <thead class="thead-dark">
      <tr>
        <th scope= "col">Bug Title</th>
        <th scope= "col">Description</th>
        <th scope= "col">Start date</th>
        <th scope= "col">Bug Screenshot</th>
        <% if current_user.role == "qa" %>
          <th scope= "col">Actions</th>
        <% end %>
        <% if current_user.role == "developer" %>
          <th scope= "col">State</th>
        <%end%>
      </tr>
    </thead>
    <tbody>
      <% @project.buggs.each do |bugg|%>
        <tr>
          <td><%= bugg.title%></td>
          <td><%= bugg.description%></td>
          <td><%= bugg.startdate%></td>
          <% if bugg.image.attached? %>
            <td><%= image_tag bugg.image, size: "75x75" %></td>
          <% else %>
            <td> <%= image_tag "download.jpeg", size: "75x75" %></td>
          <% end %>
          <% if current_user.developer? %>
            <td>
              <%= link_to bugg.state, start_working_project_bugg_path(bugg.project, bugg.id), class: "btn btn-outline-primary" if bugg.state == 'new created' %>
              <%= link_to bugg.state, in_progress_project_bugg_path(bugg.project, bugg.id), :class=>"btn btn-outline-primary" if bugg.state == 'started' %>
              <%= link_to bugg.state, completed_project_bugg_path(bugg.project, bugg.id), :class=>"btn btn-outline-primary" if bugg.state == 'inprogress' %>
              <%= link_to bugg.state, completed_project_bugg_path(bugg.project, bugg.id), :class=>"btn btn-outline-primary" if bugg.state == 'completed' %>
            </td>
          <% end %>
          <td>
            <% if current_user.role == "qa" %>
              <%= link_to "", edit_project_bugg_url(bugg.project, bugg.id), class: "fa-solid fa-pen-to-square" %>
              <%= button_to "", project_bugg_path(bugg.project,bugg.id), method: :delete, class: "fa-solid fa-trash" %>
          </td>
            <%end%>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/buggs/create.js.erb
$("#modal-window").modal('hide');
$("#permit").html("<%= j (render 'buggs/bugg_table', bugg: @buggs) %>");

app/views/buggs/edit.html.erb
<div class= "text-center">
  <h1>Edit bugg</h1>
  <%= render 'buggs/bugg', bugg: @bugg %>
</div>

app/views/buggs/index.html.erb
<h1>All Buggs</h1>
<%= link_to "New Bugg", new_project_bugg_url, class: "btn btn-primary ml-3"%>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Bugg Title</th>
      <th scope="col">Description</th>
      <th scope="col">Start date</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <%Bugg.all.each do |bugg|%>
      <tr>
        <td><%=bugg.title%></td>
        <td><%=bugg.description%></td>
        <td><%=bugg.startdate%></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/buggs/new.html.erb
<div class= "text-center">
  <h1>Create New Bugg</h1>
</div>
<%= render 'buggs/bugg', bugg: @bugg %>

app/views/buggs/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'buggs/bugg') %>");
$("#modal-window").modal('show');

app/views/dashboard/_project_table.html.erb
<% if @projects.present? %>
  <table class="table text-white ">
    <thead>
      <tr>
        <th scope="col">Project Title</th>
        <th scope="col">Description</th>
        <% if current_user.manager?%>
          <th scope="col">Developer Assigned</th>
          <th scope="col">QA Assigned</th>
        <% end %>
          <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% projects.all.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
            <% if current_user.manager?%>
              <td><%= project.users.developer.pluck(:name).join(" & ") %></td>
              <td><%= project.users.qa.pluck(:name).join(" & ") %></td>
            <% end %>
              <td>
              <div id = "deletion">
                <% if current_user.manager?%>
                  <%= link_to '', edit_project_path(project), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "fa-solid fa-pen-to-square"}  %>
                    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
                        </div>
                      </div>
                    </div>
                  <%= link_to "", project_path(project), method: :delete , class: "fa-solid fa-trash fa-1x", remote: true, data: { confirm: 'Are you sure to delete Project' } %>
                <% end %>
                  <%= link_to "", project_path(project), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: "fa-solid fa-info-circle fa-1x"}  %>
                      <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-xl" role="document">
                          <div class="modal-content">
                          </div>
                        </div>
                    </div>
                </div>
        </tr>
      <%end%>
    </tbody>
  </table>
<% else %>
  <% if current_user.developer? %>
    <strong><p><span style = "color:#8866ff;">No projects assigned yet!</span></p></strong>
  <%else%>
    <strong><p><span style = "color:#8866ff;">No projects created yet!</span></p></strong>
  <%end%>
<%end%>

app/views/dashboard/_user.html.erb
<div class = "text-black">
  <% if defined?(manager_edit)%>
    <%= link_to 'New Project', new_project_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary'}  %>
    <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class = "text-white" id="submitted">
  <%= render 'dashboard/project_table', projects: projects %>
</div>

app/views/dashboard/developer.html.erb
w<div class="container-fluid p-1 my-2 bg-dark text-white text-center">
  <h3>Developer Profile</h3>
</div>
<%= render partial: "dashboard/user", locals: { projects: @projects, disable_edit: true } %>

app/views/dashboard/home.html.erb
<% if user_signed_in? %>
  <div class= "p-1 mb-2 bg-hide text-black text-center">
    <div> Welcome! <%= current_user.name %> </div>
    <div> You are currently in  <%= current_user.role %> profile</div>
  </div>
  <div class="container p-1 mb-2 bg-hide text-white text-center ">
    <% if current_user.manager? %>
      <%= render partial: "dashboard/user", locals: { projects: @projects, manager_edit: true } %>
    <% elsif current_user.developer? %>
      <%= render partial: "dashboard/user", locals: { projects: @projects, disable_edit: true } %>
    <% else %>
      <%= render partial: "dashboard/user", locals: { projects: @projects, w_edit: true } %>
    <% end %>
    <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  </div>
<% end %>

app/views/dashboard/manager.html.erb
<div class="container-fluid p-1 my-2 bg-dark text-white text-center">
  <h3>Manager Profile</h3>
</div>
<%= render partial: "dashboard/user", locals: { projects: @projects, manager_edit: true }%>

app/views/dashboard/qa.html.erb
<div class="container-fluid p-1 my-2 bg-dark text-white text-center">
  <h3>QA Profile</h3>
</div>
<%= render partial: "dashboard/user", locals: { projects: @qa_projects, qa_edit:true }%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div>
    <a class="navbar-brand container  " href="/ ">BugZilla</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class=" collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active right" href="/ ">Home</a>
      <% if user_signed_in? %>
        <div>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger"%>
        </div>
      <%else%>
        <div>
          <%= link_to "Sign in",new_user_session_path, class:"btn btn-info"%>
          <%= link_to "Sign Up",new_user_registration_path, class:"btn btn-info"%>
        </div>
      <%end%>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src = "https://kit.fontawesome.com/aab81213bd.js" crossorigin="anonymous"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>BugZilla</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tag %>

  </head>
  <body>
    <div class="bg-image text-white" style="background-image: url('https://images.unsplash.com/photo-1477346611705-65d1883cee1e?ixlib=rb-0.3.5&amp;q=80&amp;fm=jpg&amp;crop=entropy&amp;cs=tinysrgb&amp;w=1920&amp;fit=max&amp;ixid=eyJhcHBfaWQiOjMyMDc0fQ&amp;s=c0d43804e2c7c93143fe8ff65398c8e9');height: 100vh">
      <%if user_signed_in?%>
        <%= render "layouts/navbar" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_project.html.erb
<div class= 'text-black'>
  <div class= " w-25 container 'text-black'">
    <%= form_for @project, html: {multipart: true}, remote: true do |f| %>
      <% if @project.errors.any? %>
        <h2>Errors:</h2>
        <ul>
          <%@project.errors.full_messages.each do |message|%>
          <li> <%= message %></li>
          <%end%>
        </ul>
      <%end%>
      <%= f.label :title, class: "form-label" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Enter Project title" %>

      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, class: "form-control", placeholder: "Write Project description" %>

      <%= f.label :assign_to_developer, class: "form-label" %>
      <%= f.collection_select(:user_ids, User.developer, :id, :name, {}, multiple: true, class: "form-control form-control-sm") %>

      <%= f.label :assign_to_qa, class: "form-label" %>
      <%= f.collection_select(:user_ids, User.qa, :id, :name, {}, multiple: true, class: "form-control form-control-sm") %>
      <span>
        <%= f.submit "Submit", class: "btn btn-success"%>
      </span>
   <%end%>
  </div>
</div>

app/views/projects/_show_project.html.erb
<div id= "show-`con`tent">
  <div class="container p-1 mb-2 bg-hide text-black text-center">
    <h3><%= @project.title %></h3>
    <h5><%= @project.description %></h5>
  </div>
</div>

app/views/projects/create.js.erb
$("#modal-window").modal('hide');
$("#submitted").html("<%= j (render 'dashboard/project_table', projects: @projects) %>");

app/views/projects/destroy.js.erb
$("#deletion").remove

app/views/projects/edit.html.erb
<div class= "text-center">
  <h1>Edit Project</h1>
</div>
<%= render 'projects/project', project: @project%>

app/views/projects/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'projects/project') %>");
$("#modal-window").modal('show');

app/views/projects/index.html.erb
<div class= "container ">
  <table class= "table">
      <thead>
        <tr>
          <th scope="col">Project Title</th>
          <th scope="col">Description</th>
          <th scope="col">Actions</th>
          <th scope="col">Assignee to Developer</th>
        </tr>
      </thead>
      <tbody>
        <% Project.all.each do |project|%>
          <tr>
            <td>
              <%=project.title%>
            </td>
            <td>
              <%=project.description%>
            </td>
            <td>
              <%=link_to "", edit_project_path(project), class: "fa-solid fa-pen-to-square" %>
              <%=button_to "", project_path(project), method: :delete, class: "fa-solid fa-trash" %>
            </td>
        </tr>
        <%end%>
      </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class= "text-center">
  <h1>Create New Project</h1>
</div><br>
<%= render 'projects/project' , project: @project %>

app/views/projects/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'projects/project') %>");
$("#modal-window").modal('show');

app/views/projects/show.html.erb
<%=render 'projects/show_project' , projects: projects%>


<%
=begin%>

 <% if current_user.qa? %>
  <div class = "text-center text-black">
      <%= link_to 'Create new Bugg ', new_project_bugg_url(@project),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-success'}  %>
      <div id="modal-window" class="modal hide fade" role="dialog">
        <div class="modal-dialog modal-xl" role="document">
          <div class="modal-content">
          </div>
        </div>
      </div>
  </div>
  <div class= "text-white" id="permit">
  <%= render 'buggs/bugg_table', bugg: @bugg %>
  </div>
<% end %>
<%
=end%>

app/views/projects/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'projects/show_project',projects: @projects) %>");
$("#modal-window").modal('show');